apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/application
  - config.yaml
  - release.yaml
images:
  - name: localshops-api
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-api
    digest: sha256:4a63f184f5e7764462c04d68786ef7b50f7891b8e9ea1af387d4f20340a4536c
  - name: localshops-web
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-web
    digest: sha256:c08e4dfe29868a0812e8d4762e4becfa12ec30fbc9fc915e1086aa89e17f4b69
patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: notification-worker
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
