apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/application
  - config.yaml
  - release.yaml
images:
  - name: localshops-api
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-api
    digest: sha256:514de5d1cfd65bde54310a5ee96c617f2c547127f661570720eef070315c6a84
  - name: localshops-web
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-web
    digest: sha256:de5f43b04e7b6a6d4a373fb1b67a0f3d206abfda071c1efc4da0dab025e31517
patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: notification-worker
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
