apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/application
  - config.yaml
  - release.yaml
images:
  - name: localshops-api
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-api
    digest: sha256:903227c9c97b354fda21357802d1e578cdce5b304e6da95f87df3b7054aef768
  - name: localshops-web
    newName: ocir.us-ashburn-1.oci.oraclecloud.com/idcnbp9cfade/localshops-web
    digest: sha256:73631945b6564f71364ee4d9436f751360ed317f8f96e683ab3db19e7b8dbaf7
patches:
  - target:
      kind: Deployment
      name: api
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
  - target:
      kind: Deployment
      name: notification-worker
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/hostname: node01
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
