apiVersion: v1
kind: ConfigMap
metadata:
  name: localshops-release
  labels:
    app.kubernetes.io/part-of: bhuplabs-local
data:
  environment: dev
  source-revision: "4b5e85d22968e2b7cf04ff45ebf1975f97b9e8cd"
