apiVersion: v1
kind: ConfigMap
metadata:
  name: localshops-release
  labels:
    app.kubernetes.io/part-of: bhuplabs-local
data:
  environment: dev
  source-revision: "90faceb8542a1a78d8aa1386f4c1904cb2b7a5c6"
