apiVersion: v1
kind: ConfigMap
metadata:
  name: localshops-release
  labels:
    app.kubernetes.io/part-of: bhuplabs-local
data:
  environment: dev
  source-revision: "5a85da2a11bc26525f2b16b760eb44eebbee47cd"
