apiVersion: v1
kind: PersistentVolume
metadata:
  name: localshops-dev-postgres-pv-node01
  labels:
    app.kubernetes.io/part-of: bhuplabs-local
    environment: development
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-retain
  local:
    path: /var/lib/localshops-dev/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [node01]
