apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/migration
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:4256b9e1a00eaf85175472a69d23957f83a3005c697fc01e2e9b85182e8140a9
