apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/migration
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:3a996a8db0618b2280389573814e710584825875e066b4483fc33a6f5fbb26e1
