apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localshops-dev
resources:
  - ../../../base/migration
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:ad1692ab45db9bfb905701656bb68cff46b3b61bde74cf78d7f30711c6e7d868
