apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure.yaml
  - data.yaml
  - migration.yaml
  - application.yaml
  - routes.yaml
  - production.yaml
