apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - runtime.yaml
  - application.yaml
  - migration.yaml
  - ingress.yaml
  - network-policies.yaml
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:a00129868eeba4523fc82019b969cf76bf44a4d48589dbcd84a2164826f32b79
  - name: localshops-web
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-web
    digest: sha256:5bce556e1a2a66e901f30de2f969d949f4937d74aa6565a57af6b1d6d3b293e7
