apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - runtime.yaml
  - application.yaml
  - migration.yaml
  - ingress.yaml
  - network-policies.yaml
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:9155bafcda71ae7822b0e6e36f18f5f9e44c87720767829b38d10b7fb0d9974b
  - name: localshops-web
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-web
    digest: sha256:bc93a6415b213721b8bc086baed323f0787bd6d00f263ae31100d8ba9d608f6b
