apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - runtime.yaml
  - application.yaml
  - migration.yaml
  - ingress.yaml
  - network-policies.yaml
images:
  - name: localshops-api
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-api
    digest: sha256:b68025f1e43ff9dc8058b977494634cc5a88528d29773ba7ae84c35f3213ea8d
  - name: localshops-web
    newName: hyd.ocir.io/axbcwhek7zcg/localshops-web
    digest: sha256:d6336187122036e663fd53a06ac49f7e722b916acaf3d5ce554dc2ff1788f111
